### ISSUE TITLE
Add api folder in the root

### ISSUE THREAD

**Issue by epykure** [epykure/epyk-ui#22]
Add dedicated API folder in order to simplify the structure object and not always use dictionaries.

This might help on transparency and also ensure a good structure of the input data.

**Comment by epykachu** [comment]
maybe this should come from the object itself. Say you want to do a json post, your function would turn into an object a bit like the requests framework and would look like something like so:

json_post.get_connection(args, kwargs).execute()

get_connection would then be of the form:

def get_connection(data, action, url, whatever):
    return something

This would avoid creating an extra layer of API

**Comment by epykure** [comment]
Ok I get your point but how would you implement something like this without simple API utilities:
https://www.w3schools.com/html/html5_geolocation.asp

For the geolocation the function are expecting Js function calls with as value the position.
navigator.geolocation.getCurrentPosition(showPosition)
