### ISSUE TITLE
Add the concept of HTML templates

### ISSUE THREAD

**Issue by epykure** [epykure/epyk-ui#65]
Extend the body HTML object to allow templates and simplify the creation of custom websites

**Comment by epykachu** [comment]
What about if we create something similar on the python  side to allow for completion of the template this would allow for some configurable templates. A "canvas" for the html template and a more dynamic part for the python templat

**Comment by epykure** [comment]
I am not sure what Epykure had in mind but I have done something to allow the body to be defined in a report.

I took this opportunity to fix some bugs in the module pyout.

**Comment by epykure** [comment]
If you add the below line of code to a report it should allow you to put a custom calc. Let me know if you think about something different (this will add the external packages, and allow the Javascript events)

class MyBody(Html.Body):
  def set_content(self, report, page_content):
    left = report.ui.div()
    but = report.ui.button("Click")
    but.click([
      report.js.alert("Test")
    ])
    left += but
    left.style.css.color = "white"
    right = report.ui.div("right")
    center = report.ui.div(page_content)
    div = report.ui.row([left, center, right])
    div[0].attr["class"].add("col-1")
    div[0].style.css.background_color = "grey"
    div[2].attr["class"].add("col-1")
    text = report.ui.text("text")
    text.inReport = False
    div.inReport = False
    self._html_content = "%s%s" % (div.html(), text.html())
    return self

rptObj = Report()
rptObj.body = MyBody
